//*********************************************************                                                        
//  Routes for accessing general student information        
//*********************************************************

// Create a student
POST http://localhost:3001/students HTTP/1.1
content-type: application/json

{
    "student_id": 11111,
    "first_name": "Doug",
    "last_name": "Davison", 
    "disability": "SLD R",
    "scheduledTeachers": [
        {
            "login": "cfreed01",
            "student_id": 11111,
            "role": "Other",
            "start_date": "2019-05-05",
            "end_date": "2020-03-04"
        }
    ] 
}

###

// Update a student
PUT http://localhost:3000/students/576548 HTTP/1.1
content-type: application/json

{ 
    "disability": "SLD R/W/M" 
}

###

// Delete a student
DELETE http://localhost:3000/students/576548 HTTP/1.1
content-type: application/json

###

// Get all students
GET http://localhost:3001/students/ HTTP/1.1
content-type: application/json

###

// Get all student who haven't been assigned to a TOR
GET http://localhost:3001/students/available HTTP/1.1
content-type: application/json


###

// Get a student by ID6
GET http://localhost:3001/students/576548 HTTP/1.1
content-type: application/json

###

// get backdated iep goal information for student
POST http://localhost:3001/students/3333/backdateiep HTTP/1.1
content-type: application/json

{
    "teacher": "sktras01",
    "date": "2021-07-30"
}

###

//BONUS get last calendar date in system
GET http://localhost:3001/lastdate/ HTTP/1.1
content-type: application/json

###

//Get all active iep goals for a student
GET http://localhost:3001/students/3333/allgoals HTTP/1.1
content-type: application/json

###

//Get all responses for student's current goal
GET http://localhost:3001/students/4444/responses HTTP/1.1
content-type: application/json

###

//Get attendance for student
GET http://localhost:3001/students/3333/attendance HTTP/1.1
content-type: application/json