//*********************************************************                                                        
//  Routes for accessing general teacher information        
//*********************************************************

//Create a teacher; request body includes login, secret, email, and name
POST http://localhost:3000/teachers HTTP/1.1
content-type: application/json

{
    "login": "dlpick02",
    "secret": "Picklem@n",
    "email": "dylan.pickle@teacher.com", 
    "name": "Dylan Pickle" 
}
###


//Remove test teacher here!
DELETE http://localhost:3000/teachers/dlpick02 HTTP/1.1
content-type: application/json
###


//Update teacher
PUT http://localhost:3000/teachers/dlpick02 HTTP/1.1
content-type: application/json

{
    "secret": "Chopshop234",
    "email": "dylan.pickle@teacher.com"
}

###

//Get all teachers
GET http://localhost:3000/teachers HTTP/1.1
content-type: application/json

### 

// Get a specific teacher
GET http://localhost:3000/teachers/dlpick02 HTTP/1.1
content-type: application/json

###

// Get all IEP IDs for students assigned to teacher
GET http://localhost:3000/teachers/cfreed01/dataform HTTP/1.1
content-type: application/json